Using TensorFlow backend.
Uppercase local vars:
	BATCH_SIZE: 30
	CRITIC_ITERS: 5
	DIM: 64
	ITERS: 200000
	LAMBDA: 10
	MODE: wgan-gp
	OUTPUT_DIM: 2304
Traceback (most recent call last):
  File "/home/linkermann/miniconda2/envs/MA/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension size must be evenly divisible by 4096 but is 92160 for 'Reshape_3' (op: 'Reshape') with input shapes: [30,256,4,3], [2] and with input tensors computed as partial shapes: input[1] = [?,4096].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../gan_ucf101.py", line 99, in <module>
    disc_real = Discriminator(real_data)
  File "../../gan_ucf101.py", line 90, in Discriminator
    output = tf.reshape(output, [-1, 4*4*4*DIM])
  File "/home/linkermann/miniconda2/envs/MA/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6113, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/linkermann/miniconda2/envs/MA/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/linkermann/miniconda2/envs/MA/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/linkermann/miniconda2/envs/MA/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/home/linkermann/miniconda2/envs/MA/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension size must be evenly divisible by 4096 but is 92160 for 'Reshape_3' (op: 'Reshape') with input shapes: [30,256,4,3], [2] and with input tensors computed as partial shapes: input[1] = [?,4096].
